### PR TITLE
Added some senors

### PR DESCRIPTION
**Pull request by cyberjunky**
I added some sensors which were already available in python-mind module
Rounded battery voltage to 2 decimals

### CODE REVIEW

**Comment by pathia** [comment]
Just merged these changes in locally and it works perfectly. I have the additional sensors and the battery voltage in 2 decimals precision.

**Comment by cyberjunky** [comment]
Also made it HACS compatible.

**Review by ZiroNL — APPROVED** [review]
Nice work!
Locally tested.

**Comment by cyberjunky** [comment]
@bramkragten can you have a look if you want to merge my PR? This saves me from keeping my own repo in HACS. ;P
And do you know if/how the Mind API exposes last trip stats?

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
